version: '3'

services:
  ollama:
    build:
      context: ./container
      dockerfile: Dockerfile.ollama
    ports:
      - '11434:11434'
    volumes:
      - ./src:/workdir
    tty: true
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
